################################################################################
# MAKEFILE FOR MICRO SERVICE
################################################################################

# Check essentials
ifndef IW_HOME
  $(error 'IW_HOME' is not defined. please set value for 'IW_HOME')
endif # !IW_HOME

-include $(IW_HOME)/Microservice/DCFW/service.mk
-include $(IW_HOME)/Microservice/ROFW/service.mk
-include $(IW_HOME)/Microservice/SIFW/service.mk
-include $(IW_HOME)/Microservice/SMFW/service.mk
